### ISSUE TITLE
AttributeError: 'DSGE' object has no attribute 'tmcmc'

### ISSUE THREAD

**Issue by tobiasbrammer** [gboehl/pydsge#12]
Running " p0 = mod.tmcmc(200) " results in the error in estimation_tutorial

**Comment by gboehl** [comment]
Thanks for pointing this out!

The docs where not up to date. `tmcmc` is depreciated and you can just use `prior_sampler` to sample from the prior. 

I fixed this in the documentation in [52d5e7d](https://github.com/gboehl/pydsge/commit/52d5e7d8f9bac853daa05c4f4e1a453d9d7e8d41)
