### ISSUE TITLE
DSGE Not Opening .npz file

### ISSUE THREAD

**Issue by siddharthjain0327** [gboehl/pydsge#14]
I was following the documentation and under processing estimation results, the following line failed with the error below:
`mod = DSGE.load(meta_data)
`

> ---------------------------------------------------------------------------
> ValueError                                Traceback (most recent call last)
> <ipython-input-91-45c9e418430b> in <module>
> ----> 1 mod = DSGE.load(meta_data)
> 
> ~/opt/anaconda3/lib/python3.8/site-packages/pydsge/parser.py in load(cls, npzfile, force_parse, verbose)
>     485             st = time.time()
>     486 
> --> 487         fdict = dict(np.load(npzfile, allow_pickle=True))
>     488 
>     489         mtxt = str(fdict["yaml_raw"])
> 
> ~/opt/anaconda3/lib/python3.8/site-packages/numpy/lib/npyio.py in __getitem__(self, key)
>     241             if magic == format.MAGIC_PREFIX:
>     242                 bytes = self.zip.open(key)
> --> 243                 return format.read_array(bytes,
>     244                                          allow_pickle=self.allow_pickle,
>     245                                          pickle_kwargs=self.pickle_kwargs)
> 
> ~/opt/anaconda3/lib/python3.8/site-packages/numpy/lib/format.py in read_array(fp, allow_pickle, pickle_kwargs)
>     745             pickle_kwargs = {}
>     746         try:
> --> 747             array = pickle.load(fp, **pickle_kwargs)
>     748         except UnicodeError as err:
>     749             # Friendlier error message
> 
> ~/opt/anaconda3/lib/python3.8/site-packages/scipy/stats/_distn_infrastructure.py in __setstate__(self, state)
>     623 
>     624     def __setstate__(self, state):
> --> 625         ctor_param, r = state
>     626         self.__init__(**ctor_param)
>     627         self._random_state = r
> 
> ValueError: too many values to unpack (expected 2)

I am running numpy 1.22.4 and Python 3.8.

**Comment by gboehl** [comment]
Hi Siddharth,

Thanks for reporting this. I looked into it, but it seems that this is not explicitely an issue with pydsge but rather some error with the `np.load` function with `allow_pickle=True` option. 

The automatic tests for this piece of code -- loading stored estimation results -- all go through: https://github.com/gboehl/pydsge/runs/6939625674?check_suite_focus=true

In any case, I updated the example estimation output files (`dfi_doc0*`). 

Can you confirm that the problem persists if you install the most recent version from git?

Thanks, Gregor

**Comment by gboehl** [comment]
Seems indeed as if this was a problem with python 3.8 being unable to load pickles create with 3.10. I circumvented this by reproducing some of the models functions instead of loading them (if python version < 3.10).

Would you mind checking if it works with the newly uploaded version?
