### ISSUE TITLE
Testing for 1 observable models.

### ISSUE THREAD

**Issue by Physicworld** [gboehl/pydsge#15]
im trying to run minimal dsge with inflation data for estimation and im getting a lot of errors, do you have some examples for that yaml? would be usefull!

**Comment by gboehl** [comment]
Hi and thanks for reaching out. 

Only one observable is currently not supported. I'm sure this is not too hard to fix, but I don't see any economic meaningful application for that. It should be close to impossible to identify any DSGE model with just one time series.

For now I implemented an error message to make this explicit.

**Comment by Physicworld** [comment]
Thank you for your attention, because i seen the simple nk  with just inflation observable i gonna try other model.

Thank you !!

**Comment by gboehl** [comment]
Even in the simple NK model you could at least have inflation, output and interest rates as observables.
