### ISSUE TITLE
No module named 'grgrlib.la'

### ISSUE THREAD

**Issue by superyuan2018** [gboehl/pydsge#4]
![20200619060330](https://user-images.githubusercontent.com/63491700/85112346-1355c900-b248-11ea-867d-749d35e5182d.png)

from pydsge import * # imports eg. DSGE, example, sort_nhd ...
yaml_file, data_file = example

————————————————————————————————
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-95c4031b7898> in <module>
----> 1 from pydsge import * # imports eg. DSGE, example, sort_nhd ...
      2 yaml_file, data_file = example

D:\Users\yuanxiaohui\anaconda3\lib\site-packages\pydsge\__init__.py in <module>
      4 import logging
      5 import os
----> 6 from .clsmethods import DSGE
      7 from .plots import sort_nhd
      8 from pandas.plotting import register_matplotlib_converters

D:\Users\yuanxiaohui\anaconda3\lib\site-packages\pydsge\clsmethods.py in <module>
      6 import pandas as pd
      7 from .parser import DSGE
----> 8 from .stats import summary, gfevd, mbcs_index, nhd, mdd
      9 from .plots import posteriorplot, traceplot
     10 from .mcmc import mcmc, tmcmc

D:\Users\yuanxiaohui\anaconda3\lib\site-packages\pydsge\stats.py in <module>
     11 import scipy.optimize as so
     12 from scipy.special import gammaln
---> 13 from grgrlib.core import timeprint
     14 from grgrlib.stats import mode
     15 

D:\Users\yuanxiaohui\anaconda3\lib\site-packages\grgrlib\__init__.py in <module>
      6 from .njitted import *
      7 from .optimize import *
----> 8 from .la import *

ModuleNotFoundError: No module named 'grgrlib.la'

**Comment by gboehl** [comment]
Thanks for reporting! This should be fixed with the latest commit in `grgrlib`.
