### ISSUE TITLE
need to update getting_started.ipynb

### ISSUE THREAD

**Issue by cohenimhuji** [gboehl/pydsge#8]
i think that at cell [8] you need to add falg1:

X1, (L1, K1) ,**flag1** = mod.irfs(shock_list, verbose=True)

**Comment by gboehl** [comment]
Hi and thanks for the suggestion!

This would work, but `X1, (L1, K1), _ = mod.irfs(shock_list, verbose=True)` should also work. Do you get an error when running getting_started.py?

**Comment by cohenimhuji** [comment]
Thank you very much for this package! (i look promising...)
i just try it for the first time. 

yes - the ", _" also work fine.

now i stack at cell [15]:
X1, (L1, K1), _ = mod.irfs(shock_list, pars=par0, verbose=True)
with:
ValueError: too many values to unpack (expected 2)
